name: Linux Compatibility Issue
description: Report a problem specific to running Jerry on Linux
labels: ["linux", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Jerry's Linux support! Please fill in as much detail as you can.

  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: e.g., Ubuntu 24.04, Fedora 41, Arch Linux
      placeholder: "Ubuntu 24.04"
    validations:
      required: true

  - type: input
    id: kernel-version
    attributes:
      label: Kernel Version
      description: Run `uname -r` to find this
      placeholder: "6.8.0-45-generic"
    validations:
      required: true

  - type: input
    id: shell
    attributes:
      label: Shell
      description: Which shell were you using?
      placeholder: "bash, zsh, fish"
    validations:
      required: true

  - type: input
    id: package-manager
    attributes:
      label: Package Manager
      description: e.g., apt, dnf, pacman, nix
      placeholder: "apt"
    validations:
      required: false

  - type: input
    id: claude-code-version
    attributes:
      label: Claude Code Version
      description: Run `claude --version` to find this
      placeholder: "1.0.0"
    validations:
      required: false

  - type: input
    id: uv-version
    attributes:
      label: uv Version
      description: Run `uv --version` to find this
      placeholder: "0.6.0"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the issue
      placeholder: "When I run X, I see error Y..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages if applicable)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details (screenshots, logs, workarounds found)
    validations:
      required: false
