# ORCHESTRATION.yaml
# Machine-readable orchestration state for FEAT-014 Framework Synchronization
# Document ID: PROJ-001-ORCH-STATE-FEAT014
# Version: 2.0
# Last Updated: 2026-02-17T00:00:00Z
# Schema Evolution: See docs/schemas/SCHEMA_VERSIONING.md

# Schema version for evolution support (semver format)
# Increment MAJOR for breaking changes, MINOR for additions, PATCH for fixes
schema_version: "2.0.0"

# =============================================================================
# WORKFLOW METADATA
# =============================================================================
workflow:
  id: "feat014-impl-20260217-001"
  name: "FEAT-014 Framework Synchronization Implementation"
  project_id: "PROJ-001"
  parent_epic: "EPIC-003"
  parent_feature: "FEAT-014"
  version: "2.0"
  created_at: "2026-02-17T00:00:00Z"
  updated_at: "2026-02-17T00:00:00Z"
  status: "ACTIVE"  # ACTIVE | PAUSED | COMPLETE | FAILED | CANCELLED

  # Workflow ID configuration (WI-SAO-021)
  # Supports user-specified or auto-generated identifiers
  id_source: "auto"           # "user" | "auto" - how the workflow ID was determined
  id_format: "semantic-date-seq"  # Format specification for auto-generated IDs
  # Format: {purpose}-{YYYYMMDD}-{NNN}
  # Example: feat014-impl-20260217-001

  # Orchestration pattern classification
  patterns:
    - SEQUENTIAL      # Phases execute in order
    - CONCURRENT      # Enablers within phases run in parallel
    # Single pipeline - no BARRIER_SYNC needed

  # Constraints from Jerry Constitution
  constraints:
    max_agent_nesting: 1          # P-003: Single nesting
    file_persistence: true        # P-002: All state to filesystem
    user_authority: true          # P-020: User approves gates
    max_concurrent_agents: 3      # Soft constraint (max enablers per phase)
    max_barrier_retries: 0        # Not applicable (single pipeline)
    checkpoint_frequency: "PHASE" # AGENT | PHASE | BARRIER

# =============================================================================
# PATH CONFIGURATION (WI-SAO-021)
# =============================================================================
# All paths are dynamically constructed using workflow and pipeline identifiers.
# No hardcoded pipeline names - all derived from configuration.
paths:
  # Base path for all orchestration artifacts
  base: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/"

  # Pipeline artifact path pattern (AC-012-004: Agent-level isolation)
  # {pipeline_alias} is derived from pipelines.impl.short_alias
  # {phase_id} is the phase identifier (e.g., "phase-1-core-updates")
  # {agent_id} provides isolation for parallel (fan-out) execution
  pipeline: "{base}{pipeline_alias}/{phase_id}/{agent_id}/"

  # Examples (with workflow.id = "feat014-impl-20260217-001"):
  # - Pipeline: FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-1-core-updates/en925-creator/deliverable.md

# =============================================================================
# PIPELINE DEFINITIONS
# =============================================================================
pipelines:
  # Single implementation pipeline
  impl:
    id: "pipeline-impl"
    name: "Implementation Pipeline"
    description: "Single pipeline for framework synchronization with phased enabler execution"

    # Short alias for path construction (WI-SAO-021)
    short_alias: "impl"
    skill_source: "orchestration"

    status: "PHASE_1_PENDING"  # PHASE_N_PENDING | PHASE_N_IN_PROGRESS | COMPLETE
    current_phase: 1
    total_phases: 4
    progress_percent: 0

    phases:
      - id: 1
        name: "Core Updates"
        path_id: "phase-1-core-updates"
        status: "PENDING"   # PENDING | IN_PROGRESS | COMPLETE | BLOCKED
        started_at: null
        completed_at: null
        execution_mode: "PARALLEL"
        agents:
          - id: "en925-creator"
            name: "EN-925 Agent Registry Completion - Creator"
            role: "impl"
            status: "PENDING"
            criticality: "C2"
            enabler_id: "EN-925"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-1-core-updates/en925-creator/deliverable.md"
            inputs:
              - "EN-925 enabler specification"
              - "EPIC-002/003 agent lists"
            quality:
              required_strategies: ["S-007", "S-002", "S-014"]
              optional_strategies: ["S-003", "S-010"]
              current_iteration: 0
              max_iterations: 3
              current_score: null
              target_score: 0.92

          - id: "en925-critic"
            name: "EN-925 Agent Registry Completion - Critic"
            role: "critic"
            status: "BLOCKED"
            blocked_by: "en925-creator"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-1-core-updates/en925-critic/report.md"

          - id: "en926-creator"
            name: "EN-926 Rule Synchronization - Creator"
            role: "impl"
            status: "PENDING"
            criticality: "C3"  # AE-002: touches .context/rules/
            enabler_id: "EN-926"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-1-core-updates/en926-creator/deliverable.md"
            inputs:
              - "EN-926 enabler specification"
              - "quality-enforcement.md"
              - "mandatory-skill-usage.md"
            quality:
              required_strategies: ["S-007", "S-002", "S-014", "S-004", "S-012", "S-013"]
              optional_strategies: ["S-001", "S-003", "S-010", "S-011"]
              current_iteration: 0
              max_iterations: 4  # C3 gets extra iteration
              current_score: null
              target_score: 0.92

          - id: "en926-critic"
            name: "EN-926 Rule Synchronization - Critic"
            role: "critic"
            status: "BLOCKED"
            blocked_by: "en926-creator"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-1-core-updates/en926-critic/report.md"

          - id: "en927-creator"
            name: "EN-927 Skill Documentation Completion - Creator"
            role: "impl"
            status: "PENDING"
            criticality: "C2"
            enabler_id: "EN-927"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-1-core-updates/en927-creator/deliverable.md"
            inputs:
              - "EN-927 enabler specification"
              - "skills/architecture/SKILL.md"
              - "skills/bootstrap/SKILL.md"
            quality:
              required_strategies: ["S-007", "S-002", "S-014"]
              optional_strategies: ["S-003", "S-010"]
              current_iteration: 0
              max_iterations: 3
              current_score: null
              target_score: 0.92

          - id: "en927-critic"
            name: "EN-927 Skill Documentation Completion - Critic"
            role: "critic"
            status: "BLOCKED"
            blocked_by: "en927-creator"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-1-core-updates/en927-critic/report.md"

        artifacts: []

      - id: 2
        name: "Dependent Work"
        path_id: "phase-2-dependent-work"
        status: "BLOCKED"
        blocked_by: "phase-1"
        started_at: null
        completed_at: null
        execution_mode: "PARALLEL"
        agents:
          - id: "en928-creator"
            name: "EN-928 Test Coverage Expansion - Creator"
            role: "impl"
            status: "BLOCKED"
            criticality: "C2"
            enabler_id: "EN-928"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-2-dependent-work/en928-creator/deliverable.md"
            inputs:
              - "EN-928 enabler specification"
              - "tests/ directory"
              - "EN-925/926 results (for agent list and rules)"
            quality:
              required_strategies: ["S-007", "S-002", "S-014"]
              optional_strategies: ["S-003", "S-010"]
              current_iteration: 0
              max_iterations: 3
              current_score: null
              target_score: 0.92

          - id: "en928-critic"
            name: "EN-928 Test Coverage Expansion - Critic"
            role: "critic"
            status: "BLOCKED"
            blocked_by: "en928-creator"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-2-dependent-work/en928-critic/report.md"

          - id: "en929-creator"
            name: "EN-929 Minor Documentation Cleanup - Creator"
            role: "impl"
            status: "BLOCKED"
            criticality: "C2"
            enabler_id: "EN-929"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-2-dependent-work/en929-creator/deliverable.md"
            inputs:
              - "EN-929 enabler specification"
              - "Various documentation files"
            quality:
              required_strategies: ["S-007", "S-002", "S-014"]
              optional_strategies: ["S-003", "S-010"]
              current_iteration: 0
              max_iterations: 3
              current_score: null
              target_score: 0.92

          - id: "en929-critic"
            name: "EN-929 Minor Documentation Cleanup - Critic"
            role: "critic"
            status: "BLOCKED"
            blocked_by: "en929-creator"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-2-dependent-work/en929-critic/report.md"

        artifacts: []

      - id: 3
        name: "Verification"
        path_id: "phase-3-verification"
        status: "BLOCKED"
        blocked_by: "phase-2"
        started_at: null
        completed_at: null
        execution_mode: "SEQUENTIAL"
        agents:
          - id: "verifier"
            name: "Integration Verifier"
            role: "impl"
            status: "BLOCKED"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-3-verification/verifier/report.md"
            inputs:
              - "All Phase 1-2 changes"
            tasks:
              - "Run full test suite (uv run pytest tests/)"
              - "Run ruff check (uv run ruff check src/)"
              - "Run mypy if applicable"
              - "Manual verification of AGENTS.md, rules/, skill docs"
              - "Verify pre-commit hooks pass"

        artifacts: []

      - id: 4
        name: "Synthesis"
        path_id: "phase-4-synthesis"
        status: "BLOCKED"
        blocked_by: "phase-3"
        started_at: null
        completed_at: null
        execution_mode: "SEQUENTIAL"
        agents:
          - id: "synthesizer"
            name: "FEAT-014 Synthesizer"
            role: "orch-synthesizer"
            status: "BLOCKED"
            artifact: "FEAT-014-framework-synchronization/orchestration/feat014-impl-20260217-001/impl/phase-4-synthesis/synthesis/FEAT-014-final-synthesis.md"
            inputs:
              - "All phase results"
              - "Quality metrics from ORCHESTRATION.yaml"
              - "Verification report"
            outputs:
              - "Final Synthesis document"
              - "FEAT-014 worktracker update"
              - "EPIC-003 rollup update"

        artifacts: []

# =============================================================================
# EXECUTION QUEUE
# =============================================================================
execution_queue:
  current_group: 1
  groups:
    - id: 1
      name: "Phase 1 Creator Agents"
      execution_mode: "PARALLEL"
      status: "READY"  # READY | IN_PROGRESS | COMPLETE | BLOCKED
      agents:
        - "en925-creator"
        - "en926-creator"
        - "en927-creator"

    - id: 2
      name: "Phase 1 Critic Cycles"
      execution_mode: "SEQUENTIAL"  # Each enabler's creator-critic cycle runs independently
      status: "BLOCKED"
      blocked_by: "group-1"
      agent_pairs:
        - creator: "en925-creator"
          critic: "en925-critic"
          iterations_remaining: 3
        - creator: "en926-creator"
          critic: "en926-critic"
          iterations_remaining: 4  # C3 gets extra
        - creator: "en927-creator"
          critic: "en927-critic"
          iterations_remaining: 3

    - id: 3
      name: "Phase 2 Creator Agents"
      execution_mode: "PARALLEL"
      status: "BLOCKED"
      blocked_by: "group-2"
      agents:
        - "en928-creator"
        - "en929-creator"

    - id: 4
      name: "Phase 2 Critic Cycles"
      execution_mode: "SEQUENTIAL"
      status: "BLOCKED"
      blocked_by: "group-3"
      agent_pairs:
        - creator: "en928-creator"
          critic: "en928-critic"
          iterations_remaining: 3
        - creator: "en929-creator"
          critic: "en929-critic"
          iterations_remaining: 3

    - id: 5
      name: "Phase 3 Verification"
      execution_mode: "SEQUENTIAL"
      status: "BLOCKED"
      blocked_by: "group-4"
      agents:
        - "verifier"

    - id: 6
      name: "Phase 4 Synthesis"
      execution_mode: "SEQUENTIAL"
      status: "BLOCKED"
      blocked_by: "group-5"
      agents:
        - "synthesizer"

# =============================================================================
# QUALITY TRACKING
# =============================================================================
quality:
  # Per-enabler quality metrics
  enablers:
    en925:
      id: "EN-925"
      title: "Agent Registry Completion"
      criticality: "C2"
      target_score: 0.92
      current_score: null
      iterations_completed: 0
      max_iterations: 3
      status: "PENDING"  # PENDING | IN_PROGRESS | PASS | REVISE | ESCALATED
      dimension_scores:
        completeness: null
        internal_consistency: null
        methodological_rigor: null
        evidence_quality: null
        actionability: null
        traceability: null

    en926:
      id: "EN-926"
      title: "Rule Synchronization"
      criticality: "C3"  # AE-002: touches .context/rules/
      target_score: 0.92
      current_score: null
      iterations_completed: 0
      max_iterations: 4  # C3 gets extra iteration
      status: "PENDING"
      dimension_scores:
        completeness: null
        internal_consistency: null
        methodological_rigor: null
        evidence_quality: null
        actionability: null
        traceability: null
      escalation_reason: "AE-002 - Modifies .context/rules/mandatory-skill-usage.md"

    en927:
      id: "EN-927"
      title: "Skill Documentation Completion"
      criticality: "C2"
      target_score: 0.92
      current_score: null
      iterations_completed: 0
      max_iterations: 3
      status: "PENDING"
      dimension_scores:
        completeness: null
        internal_consistency: null
        methodological_rigor: null
        evidence_quality: null
        actionability: null
        traceability: null

    en928:
      id: "EN-928"
      title: "Test Coverage Expansion"
      criticality: "C2"
      target_score: 0.92
      current_score: null
      iterations_completed: 0
      max_iterations: 3
      status: "PENDING"
      dimension_scores:
        completeness: null
        internal_consistency: null
        methodological_rigor: null
        evidence_quality: null
        actionability: null
        traceability: null

    en929:
      id: "EN-929"
      title: "Minor Documentation Cleanup"
      criticality: "C2"
      target_score: 0.92
      current_score: null
      iterations_completed: 0
      max_iterations: 3
      status: "PENDING"
      dimension_scores:
        completeness: null
        internal_consistency: null
        methodological_rigor: null
        evidence_quality: null
        actionability: null
        traceability: null

  # Aggregate quality metrics
  aggregate:
    enablers_total: 5
    enablers_pass: 0
    enablers_revise: 0
    enablers_pending: 5
    pass_rate: 0.0
    average_score: null
    lowest_score: null
    highest_score: null

# =============================================================================
# CHECKPOINTS
# =============================================================================
checkpoints:
  latest_id: null
  entries: []
  # Example entry:
  # - id: "CP-001"
  #   timestamp: "2026-02-17T12:00:00Z"
  #   trigger: "PHASE_COMPLETE"  # PHASE_COMPLETE | MANUAL
  #   description: "Phase 1 Core Updates complete"
  #   recovery_point: "phase-2-start"
  #   phase_id: 1
  #   enablers_complete: ["EN-925", "EN-926", "EN-927"]

# =============================================================================
# METRICS
# =============================================================================
metrics:
  execution:
    phases_complete: 0
    phases_total: 4
    phases_percent: 0
    enablers_complete: 0
    enablers_total: 5
    enablers_percent: 0
    agents_executed: 0
    agents_total: 12  # 10 creator/critic pairs + verifier + synthesizer
    agents_percent: 0
    artifacts_created: 0
    artifacts_total: 11  # 5 creator + 5 critic + 1 verifier + 1 synthesis
    artifacts_percent: 0

  quality:
    agent_success_rate: 0
    average_iterations_per_enabler: 0
    checkpoint_recovery_tested: false

  timing:
    workflow_started: null
    last_activity: null
    estimated_completion: null

# =============================================================================
# BLOCKERS AND ISSUES
# =============================================================================
blockers:
  active: []
  # Example:
  # - id: "BLK-001"
  #   description: "EN-926 failed to reach 0.92 after 4 iterations"
  #   blocking: ["phase-1"]
  #   severity: "HIGH"  # LOW | MEDIUM | HIGH
  #   created_at: "2026-02-17T10:00:00Z"
  #   escalation_required: true

issues:
  resolved: []
  # Example:
  # - id: "ISS-001"
  #   description: "Issue description"
  #   resolution: "How it was resolved"
  #   resolved_at: "2026-02-17T11:00:00Z"

# =============================================================================
# NEXT ACTIONS
# =============================================================================
next_actions:
  immediate:
    - action: "Execute Phase 1 creator agents in parallel"
      agents: ["en925-creator", "en926-creator", "en927-creator"]
      execution_mode: "PARALLEL"

  subsequent:
    - action: "Run creator-critic cycles for Phase 1 enablers"
      depends_on: "Phase 1 creators complete"
      max_iterations: "3 (C2) or 4 (C3 for EN-926)"
    - action: "Create CP-001 checkpoint"
      depends_on: "Phase 1 complete"
    - action: "Execute Phase 2 creator agents"
      depends_on: "CP-001 verified"

# =============================================================================
# RESUMPTION CONTEXT
# =============================================================================
resumption:
  last_checkpoint: null
  current_state: "Workflow not started"
  next_step: "Execute Phase 1 creator agents in parallel"

  files_to_read:
    - "ORCHESTRATION_PLAN.md"           # Strategic context
    - "ORCHESTRATION_WORKTRACKER.md"    # Tactical documentation
    - "ORCHESTRATION.yaml"              # This file - machine-readable state
    - "EN-925 through EN-929 enabler specifications"

  cross_session_portable: true
  ephemeral_references: false
