FROM golang:1.22-alpine AS builder
RUN go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest && \
    go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest && \
    go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest && \
    go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest && \
    go install -v github.com/projectdiscovery/katana/cmd/katana@latest && \
    go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest

FROM alpine:3.19
COPY --from=builder /go/bin/* /usr/local/bin/
RUN apk add --no-cache ca-certificates
WORKDIR /work
ENTRYPOINT ["/bin/sh"]
