# ORCHESTRATION.yaml
# Machine-readable orchestration state for FEAT-010 Tournament Remediation
# Document ID: PROJ-001-ORCH-STATE-FEAT010
# Version: 2.0
# Last Updated: 2026-02-15

schema_version: "2.0.0"

# =============================================================================
# WORKFLOW METADATA
# =============================================================================
workflow:
  id: "feat010-remediation-20260215-001"
  name: "FEAT-010 Tournament Remediation"
  project_id: "PROJ-001-oss-release"
  version: "2.0"
  created_at: "2026-02-15T00:00:00Z"
  updated_at: "2026-02-15T00:00:00Z"
  status: "ACTIVE"

  id_source: "auto"
  id_format: "semantic-date-seq"

  patterns:
    - SEQUENTIAL
    - CONCURRENT  # Enablers within phases run in parallel

  constraints:
    max_agent_nesting: 1          # P-003: Single nesting
    file_persistence: true        # P-002: All state to filesystem
    user_authority: true          # P-020: User approves gates
    max_concurrent_agents: 3      # Max parallel enablers per phase
    max_iterations_per_enabler: 4 # User directive (override of default 3)
    checkpoint_frequency: "PHASE"

# =============================================================================
# QUALITY CONFIGURATION (C4)
# =============================================================================
quality:
  criticality: "C4"
  threshold: 0.92
  scoring_mechanism: "S-014"
  max_iterations: 4
  human_escalation_after: 4

  strategies_required:
    - "S-001"  # Red Team
    - "S-002"  # Devil's Advocate
    - "S-003"  # Steelman
    - "S-004"  # Pre-Mortem
    - "S-007"  # Constitutional AI
    - "S-010"  # Self-Refine
    - "S-011"  # CoVe
    - "S-012"  # FMEA
    - "S-013"  # Inversion
    - "S-014"  # LLM-as-Judge

  scoring_dimensions:
    completeness: { weight: 0.20, min: 0.88 }
    internal_consistency: { weight: 0.20, min: 0.88 }
    methodological_rigor: { weight: 0.20, min: 0.88 }
    evidence_quality: { weight: 0.15, min: 0.85 }
    actionability: { weight: 0.15, min: 0.85 }
    traceability: { weight: 0.10, min: 0.85 }

  enabler_scores:
    EN-813: { score: null, iterations: 0, status: "PENDING" }
    EN-814: { score: null, iterations: 0, status: "PENDING" }
    EN-815: { score: null, iterations: 0, status: "PENDING" }
    EN-816: { score: null, iterations: 0, status: "PENDING" }
    EN-817: { score: null, iterations: 0, status: "PENDING" }
    EN-818: { score: null, iterations: 0, status: "PENDING" }
    EN-819: { score: null, iterations: 0, status: "PENDING" }

  workflow_quality:
    average_score: null
    lowest_score: null
    total_iterations: 0
    gates_passed: 0
    gates_failed: 0
    feat009_rescore: null

# =============================================================================
# PATH CONFIGURATION
# =============================================================================
paths:
  base: "FEAT-010-tournament-remediation/orchestration/feat010-remediation-20260215-001/"
  impl: "{base}impl/"
  synthesis: "{base}synthesis/"
  checkpoints: "{base}checkpoints/"

# =============================================================================
# PIPELINE DEFINITION (Single Pipeline)
# =============================================================================
pipeline:
  id: "remediation"
  name: "FEAT-010 Tournament Remediation Pipeline"
  short_alias: "impl"
  status: "PHASE_1_PENDING"
  current_phase: 1
  total_phases: 4
  progress_percent: 0

  phases:
    - id: 1
      name: "P0 Critical Fixes"
      path_id: "phase-1-p0-critical"
      status: "PENDING"
      started_at: null
      completed_at: null
      enablers:
        - id: "EN-813"
          name: "Template Context Optimization"
          status: "PENDING"
          effort: 5
          tasks: 4
          findings: ["T-001"]
          iterations: 0
          score: null
          creator_agent: null
          critic_agent: null

        - id: "EN-814"
          name: "Finding ID Scoping & Uniqueness"
          status: "PENDING"
          effort: 3
          tasks: 3
          findings: ["T-002"]
          iterations: 0
          score: null
          creator_agent: null
          critic_agent: null

        - id: "EN-815"
          name: "Documentation & Navigation Fixes"
          status: "PENDING"
          effort: 2
          tasks: 5
          findings: ["T-007", "T-023", "T-026", "T-027", "T-028"]
          iterations: 0
          score: null
          creator_agent: null
          critic_agent: null

    - id: 2
      name: "P1 Documentation & Runtime"
      path_id: "phase-2-p1-docs-runtime"
      status: "BLOCKED"
      blocked_by: "phase-1"
      started_at: null
      completed_at: null
      enablers:
        - id: "EN-816"
          name: "Skill Documentation Completeness"
          status: "PENDING"
          effort: 3
          tasks: 4
          findings: ["T-008", "T-014", "T-022"]
          iterations: 0
          score: null
          creator_agent: null
          critic_agent: null

        - id: "EN-817"
          name: "Runtime Enforcement"
          status: "PENDING"
          effort: 5
          tasks: 5
          findings: ["T-004", "T-006", "T-009"]
          iterations: 0
          score: null
          creator_agent: null
          critic_agent: null

    - id: 3
      name: "P1 CI & SSOT"
      path_id: "phase-3-p1-ci-ssot"
      status: "BLOCKED"
      blocked_by: "phase-2"
      started_at: null
      completed_at: null
      enablers:
        - id: "EN-818"
          name: "Template Validation CI Gate"
          status: "PENDING"
          effort: 5
          tasks: 4
          findings: ["T-005", "T-003"]
          iterations: 0
          score: null
          creator_agent: null
          critic_agent: null

        - id: "EN-819"
          name: "SSOT Consistency & Template Resilience"
          status: "PENDING"
          effort: 3
          tasks: 4
          findings: ["T-017", "T-016"]
          iterations: 0
          score: null
          creator_agent: null
          critic_agent: null

    - id: 4
      name: "Integration Validation & Synthesis"
      path_id: "phase-4-integration"
      status: "BLOCKED"
      blocked_by: "phase-3"
      started_at: null
      completed_at: null
      steps:
        - id: "4.1"
          name: "Full E2E test suite"
          status: "PENDING"
          command: "uv run pytest tests/e2e/ -v"

        - id: "4.2"
          name: "Ruff + type checks"
          status: "PENDING"
          command: "uv run ruff check src/"

        - id: "4.3"
          name: "Re-score FEAT-009 with S-014"
          status: "PENDING"
          agent: "feat009-rescorer"

        - id: "4.4"
          name: "Create Final Synthesis"
          status: "PENDING"
          agent: "feat010-synthesizer"

        - id: "4.5"
          name: "Update FEAT-010 worktracker"
          status: "PENDING"

# =============================================================================
# EXECUTION QUEUE
# =============================================================================
execution_queue:
  current_group: 1
  groups:
    - id: 1
      name: "Phase 1: EN-813 + EN-814 + EN-815 (parallel creators)"
      execution_mode: "PARALLEL"
      status: "READY"
      agents:
        - "en813-creator"
        - "en814-creator"
        - "en815-creator"

    - id: 2
      name: "Phase 1: Critic cycles (parallel per enabler)"
      execution_mode: "PARALLEL"
      status: "BLOCKED"
      blocked_by: "group-1"
      agents:
        - "en813-critic"
        - "en814-critic"
        - "en815-critic"

    - id: 3
      name: "Phase 1: Revision cycles (if needed)"
      execution_mode: "PARALLEL"
      status: "BLOCKED"
      blocked_by: "group-2"
      note: "Only for enablers scoring < 0.92. Up to 3 more iterations."

    - id: 4
      name: "Phase 2: EN-816 + EN-817 (parallel creators)"
      execution_mode: "PARALLEL"
      status: "BLOCKED"
      blocked_by: "phase-1-complete"
      agents:
        - "en816-creator"
        - "en817-creator"

    - id: 5
      name: "Phase 2: Critic + revision cycles"
      execution_mode: "PARALLEL"
      status: "BLOCKED"
      blocked_by: "group-4"

    - id: 6
      name: "Phase 3: EN-818 + EN-819 (parallel creators)"
      execution_mode: "PARALLEL"
      status: "BLOCKED"
      blocked_by: "phase-2-complete"
      agents:
        - "en818-creator"
        - "en819-creator"

    - id: 7
      name: "Phase 3: Critic + revision cycles"
      execution_mode: "PARALLEL"
      status: "BLOCKED"
      blocked_by: "group-6"

    - id: 8
      name: "Phase 4: Integration validation"
      execution_mode: "SEQUENTIAL"
      status: "BLOCKED"
      blocked_by: "phase-3-complete"

# =============================================================================
# CHECKPOINTS
# =============================================================================
checkpoints:
  latest_id: null
  entries: []

# =============================================================================
# METRICS
# =============================================================================
metrics:
  execution:
    phases_complete: 0
    phases_total: 4
    phases_percent: 0
    enablers_complete: 0
    enablers_total: 7
    enablers_percent: 0
    tasks_complete: 0
    tasks_total: 29
    tasks_percent: 0

  quality:
    average_enabler_score: null
    lowest_enabler_score: null
    total_iterations: 0
    human_escalations: 0

  timing:
    workflow_started: null
    last_activity: null
    estimated_completion: null

# =============================================================================
# BLOCKERS AND ISSUES
# =============================================================================
blockers:
  active: []

issues:
  resolved: []

# =============================================================================
# NEXT ACTIONS
# =============================================================================
next_actions:
  immediate:
    - action: "Execute Phase 1 creator agents for EN-813, EN-814, EN-815"
      execution_mode: "PARALLEL"

  subsequent:
    - action: "Run critic cycles for Phase 1 enablers"
      depends_on: "Phase 1 creators complete"
    - action: "Execute Phase 2 upon Phase 1 completion"
      depends_on: "Phase 1 all enablers >= 0.92"

# =============================================================================
# RESUMPTION CONTEXT
# =============================================================================
resumption:
  last_checkpoint: null
  current_state: "Workflow not started"
  next_step: "Execute Phase 1 creator agents"

  files_to_read:
    - "ORCHESTRATION_PLAN.md"
    - "ORCHESTRATION_WORKTRACKER.md"
    - "ORCHESTRATION.yaml"

  cross_session_portable: true
  ephemeral_references: false
